title: IES Benigaslo - Erasmus 25-26
description: Erasmus VET Project 2025-2026
theme: just-the-docs

url: https://benigaslo.github.io/Erasmus/
baseurl: "/Erasmus" 

aux_links:
  ISS Pertini Anelli: https://unica.istruzione.gov.it/cercalatuascuola/istituti/BAIS071002/iiss-pertinianellipinto/
