title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://benigaslo.github.io/Erasmus/
baseurl: "/Erasmus" 

aux_links:
  ISS Pertini Anelli: https://unica.istruzione.gov.it/cercalatuascuola/istituti/BAIS071002/iiss-pertinianellipinto/
